# Generated by Django 4.2 on 2023-04-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200, null=True)),
                ('patient_phone', models.CharField(max_length=12, null=True)),
                ('patient_address', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_details', models.CharField(max_length=500, null=True)),
                ('activity', models.CharField(max_length=500, null=True)),
                ('amount', models.IntegerField(max_length=200, null=True)),
                ('gst', models.IntegerField(max_length=100, null=True)),
                ('total_amount', models.IntegerField(max_length=200, null=True)),
                ('status', models.CharField(max_length=200, null=True)),
                ('time_stamp', models.TimeField()),
                ('date_field', models.DateField()),
            ],
        ),
    ]
