# Generated by Django 4.2 on 2023-04-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_info',
            name='gst',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='payment_info',
            name='total_amount',
            field=models.IntegerField(null=True),
        ),
    ]
