# Generated by Django 4.2 on 2023-04-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_payment_info_gst_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_info',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
