# Generated by Django 4.2 on 2023-04-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_payment_info_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_info',
            name='date_field',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payment_info',
            name='time_stamp',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
