# Generated by Django 4.2 on 2023-04-29 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_payment_info_date_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_info',
            name='patient_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.patient_info'),
        ),
    ]
