# Generated by Django 4.2 on 2023-04-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_payment_info_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_info',
            name='activity',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='payment_info',
            name='payment_details',
            field=models.TextField(null=True),
        ),
    ]
