# Generated by Django 4.2 on 2023-04-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_payment_info_activity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_info',
            name='date_field',
        ),
        migrations.AlterField(
            model_name='payment_info',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
