# Generated by Django 4.2 on 2023-04-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_payment_info_date_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_info',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
