# Generated by Django 4.2 on 2023-05-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_payment_info_time_stamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.IntegerField(max_length=15)),
                ('gst', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='payment_info',
            old_name='gst',
            new_name='c_gst',
        ),
        migrations.AddField(
            model_name='patient_info',
            name='patient_gst_no',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='payment_info',
            name='s_gst',
            field=models.IntegerField(null=True),
        ),
    ]
