# Generated by Django 4.2 on 2023-05-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_merchant_rename_gst_payment_info_c_gst_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_info',
            name='patient_address',
        ),
        migrations.AddField(
            model_name='payment_info',
            name='billing_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
