# Generated by Django 4.2 on 2023-05-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_patient_info_patient_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_info',
            name='amount',
        ),
        migrations.AddField(
            model_name='merchant',
            name='c_gst',
            field=models.IntegerField(blank=True, default=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merchant',
            name='s_gst',
            field=models.IntegerField(default=9),
            preserve_default=False,
        ),
    ]
