# Generated by Django 4.2 on 2023-05-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_payment_info_amount_merchant_c_gst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_info',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient_info',
            name='patient_address_2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patient_info',
            name='patient_adress_1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patient_info',
            name='pin',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='patient_info',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient_info',
            name='patient_phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
