# Generated by Django 4.2 on 2023-05-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_rename_billing_address_payment_info_billing_address_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_info',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
