# Generated by Django 4.2 on 2023-05-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_payment_info_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_info',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
